### ISSUE TITLE
[Crash]: Trading Post crashes game when near villagers and clicked on it

### ISSUE THREAD

**Issue by NekiChan** [Fuzss/tradingpost#12]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

TradingPost v.4.0.0-1.19-Fabric

### Notes (Required)

1. Put the tradingpost table nearby villagers/wandering trader
2. I click on it
3.  The game crashes

### Crash Report (Required)

https://gist.github.com/NekiChan/a644b581936d0f14e95c4e2f7c8b404a

**Comment by Fuzss** [comment]
update trading post to the latest version for 1.19
