### ISSUE TITLE
[Suggestion]: Auto Trading similar to Bartering Station

### ISSUE THREAD

**Issue by LeftChaotix** [Fuzss/tradingpost#14]
### Suggestion (Required)

This mod is an awesome way to bring a trading hall together, being able to access all trades in an area from one block is incredible, however you still have to go through and make every trade manually. Having the ability to select a trade in the gui, and then pipe in the items required to fulfill that trade and then finally pipe out the result. This could be a function for the default trading post, or potentially something for an upgraded version. This may be out of the original scope for the mod, but it would make it a great sister-mod to your Bartering Station, which allows for automated bartering.

**Comment by Fuzss** [comment]
Thanks for the suggestion!

I thought about this before, but it is unfortunately out of scope for this mod. Such a mechanic would require most of the  mod to be rewritten from scratch. I'm also very happy with the way the mod is laid out currently, where it's most of all a nice utility to get a quick and accessibly overview of all the villagers around you.

I'd recommend checking out the Easy Villagers mod though, I think it's capable of doing automatic trading for you.
