### ISSUE TITLE
[Suggestion]: Port to 1.20.1

### ISSUE THREAD

**Issue by WnndGws** [Fuzss/tradingpost#16]
### Suggestion (Required)

I love this mod (along with Bartering Stations), but run 1.20.1 on my Server

Not sure how hard/easy an upgrade would be, and if I knew ANYTHING about JS I would do it myself lol

**Comment by noah1510** [comment]
If you use the fabric version just open the jar with 7zip and change the minecraft version in the fabric.mod.json file.
You have to do this for both trading post and puzzles lib.

1.20.1 didn't have any API changes so this should work without any problems (at least it works for me).
