### ISSUE TITLE
[Bug]: Search bar doesn't accept input

### ISSUE THREAD

**Issue by juntaoliAtUNC** [Fuzss/tradingpost#19]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Current behavior: Cannot interact with the search bar on top of the trading post interface
Steps to reproduce: right click on a trading post and try to use the search bar. It doesn't accept input.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in latest version.
