### ISSUE TITLE
[Suggestion]: compatibility with Infinite Trading mod

### ISSUE THREAD

**Issue by Nycto97** [Fuzss/tradingpost#20]
### Suggestion (Required)

I noticed the following:

[Infinite Trading](https://modrinth.com/mod/infinite-trading) removes the trading cap on trades with a villager.
This still works when both mods are installed, but only when trading with the villagers themselves.

Trading via Trading Post will still have a cap/limit on trades.

Is it possible to make these 2 mods compatible?

_Extra info:
Minecraft: 1.19.2
Forge: 43.3.2
Trading Post v4.2.0
Infinite Trading v4.0_

Kind regards,
Nycto

**Comment by Fuzss** [comment]
Infinite Trading seems to reset trades when clicking on the villager. This doesn't work with Trading Post.

There are more ideal implementations like cancelling `MerchantOffer::increaseUses` which would work out of the box.
