### ISSUE TITLE
Crash on search in trading post

### ISSUE THREAD

**Issue by Zach67** [Fuzss/tradingpost#4]
When I search certain enchants in the trading post my game crashes. (See crash log)
[crash-2021-12-26_11.56.53-client.txt](https://github.com/Fuzss/tradingpost/files/7777289/crash-2021-12-26_11.56.53-client.txt)
.

**Comment by Zach67** [comment]
https://pastebin.com/bR0vBTBf

^pastebin if you don't want to download the .txt file.

**Comment by Fuzss** [comment]
Which enchants exactly, I mean what exactly did you type that made the game crash?

**Comment by Zach67** [comment]
I typed "luck" and it showed three results then crashed immediately.

**Comment by Fuzss** [comment]
Looked into it, that's a bug with the [Blue Skies](https://www.curseforge.com/minecraft/mc-mods/blue-skies) mod.
I created an issue on their bug tracker, let's hope they'll fix it soon: https://gitlab.com/modding-legacy/blue-skies/-/issues/84
