### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Potatomonium** [Fuzss/tradingpost#6]
I placed a trading post in a village and right-clicked it, but nothing happened. when looking at the block with the Jade mod, it showed as being a dirt block.

Breaking the block left an invisible block, breaking the dirt block beneath did nothing but on placing the dirt block underneath again, the Trading Post appeared very briefly and the server crashed.

Occurred after updating to PuzzlesLib - v3.13, Placebo - 6.0.3, CraftingTweaks - 14.0.2, Aquaculture - 2.3.2, Balm - 2.4.0+0, Citadel - 1.10.8 

Server Crash log
https://github.com/Potatomonium/Trading-post-Crash/blob/main/Server%20Log

**Comment by Potatomonium** [comment]
On starting the server again, the Trading post works as intended

**Comment by Fuzss** [comment]
Can you upload the debug.log file? It's in the same location as latest.log.

**Comment by Potatomonium** [comment]
Sorry, I'm not real good at knowing all this stuff. I couldn't find any debug.log file in the logs folder, but I found this in the crash-reports folder. Hope this is what you need

https://github.com/Potatomonium/Server-Crash-Report/blob/main/Crash%20Report1

**Comment by Fuzss** [comment]
No worries, we'll get there. That's not the file I need unfortunately.
In the folder where you run your server, there is a folder called `logs`. In there is a file called `latest.log`, that's the one you already sent to me. Now what I need is the file called `debug.log`.
And you don't have to make a new Github repo every time you upload a file, you can simply use a site such as this and then share the link with me: https://pastebin.com/

**Comment by Potatomonium** [comment]
There're no files called debug.log in the logs folder. there are zipped folders called 2021-30-12-2.log.gz, 2021-30-12-1.log.gz and so on. In those are log files

https://github.com/Potatomonium/Hope/blob/main/Server%20Log

I posted in GitHub again because this text was too large for Pastebin and I'm not sure what parts you need.  I hope I got the right file this time

**Comment by Potatomonium** [comment]
It works perfectly now

**Comment by Fuzss** [comment]
That’s what I wanted to hear, thank you!
