### ISSUE TITLE
[Bug]: /config is not available 

### ISSUE THREAD

**Issue by TheCherry** [Fuzss/tradingpost#8]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.0.0

### Notes (Required)

I am not able to find a config file on our server - neither is a /config command available.
ForgeConfigAPIPort-v4.0.0-1.19-Fabric.jar
is installed too.

**Comment by Fuzss** [comment]
The command is not designed for dedicated servers. The server config file is located in the world save, so probably `/world/serverconfigs/tradingpost-server.toml`.

**Comment by TheCherry** [comment]
ok - would be good if place the configs in /configs/ like all other mods too ...
or at last write that in the description by curseforge
