### ISSUE TITLE
[Crash]: Crash during startup

### ISSUE THREAD

**Issue by Baggytrousers27** [Fuzss/tradingpost#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

TradingPost-v4.0.1-1.19-Forge

### Notes (Required)

Forge 1.19.1 42.0.1
PuzzlesLib-v4.1.4-1.19.1-Forge
TradingPost-v4.0.1-1.19-Forge

java.lang.NoClassDefFoundError: fuzs/puzzleslib/config/ConfigHolderV2

Debug log included in crash report gist.

### Crash Report (Required)

https://gist.github.com/Baggytrousers27/085010d3f087940333ce8da242b2145f

**Comment by Fuzss** [comment]
Please use the correct Trading Post version for Minecraft 1.19.1

**Comment by Baggytrousers27** [comment]
An absolute goose is me.
Sorry.
